development:
  adapter: async

test:
  adapter: async


production:
  adapter: postgresql
  url: postgres://pzdphzffxvgugf:-hSziHfkxieE4ODT2KVqjyLmca@ec2-23-23-95-27.compute-1.amazonaws.com:5432/deute7a7jcdej0
