# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61592f6b905e6399b1140a8e71df9db079fd4783566e4a159fa86331c2e06d82f27cf127fb9bbe607b16e6e62575351488c8a94f6fc818d9fbe6d4bf294251fd

test:
  secret_key_base: 4327deddfca7e6a552e72b4d841615118e771209b0f6e43864ccfc7444de9d5717d8c33d4033042bd372d83f1b00896d350f7e0fc4744038e648fb786aab7bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
